// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZp6BmD-HkHaIBrrOeFs9sNTVS5fdvnOA',
    appId: '1:404046991954:web:53cea0689bbce86e66058b',
    messagingSenderId: '404046991954',
    projectId: 'flutter-zartek',
    authDomain: 'flutter-zartek.firebaseapp.com',
    storageBucket: 'flutter-zartek.appspot.com',
    measurementId: 'G-5TN9Y4XD5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRQEYvi2COqi8w159p_hRNkyhkVO6fRys',
    appId: '1:404046991954:android:713a85cfcee7bfb166058b',
    messagingSenderId: '404046991954',
    projectId: 'flutter-zartek',
    storageBucket: 'flutter-zartek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxBgn1VKBz8nmNcpBvCE5fzqQu0VgFxRg',
    appId: '1:404046991954:ios:5c1c5f7fc40b18cb66058b',
    messagingSenderId: '404046991954',
    projectId: 'flutter-zartek',
    storageBucket: 'flutter-zartek.appspot.com',
    androidClientId: '404046991954-0j2pm55jvm3s10gd54mlg4bomver8j3f.apps.googleusercontent.com',
    iosClientId: '404046991954-1en2uh7mboeeulai12k4eugmnk5prvlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterZartekTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxBgn1VKBz8nmNcpBvCE5fzqQu0VgFxRg',
    appId: '1:404046991954:ios:5c1c5f7fc40b18cb66058b',
    messagingSenderId: '404046991954',
    projectId: 'flutter-zartek',
    storageBucket: 'flutter-zartek.appspot.com',
    androidClientId: '404046991954-0j2pm55jvm3s10gd54mlg4bomver8j3f.apps.googleusercontent.com',
    iosClientId: '404046991954-1en2uh7mboeeulai12k4eugmnk5prvlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterZartekTest',
  );
}
